### ISSUE TITLE
Exceptions for algebra

### ISSUE THREAD

**Issue by MAGP116** [dariomtz/Machine-Learning-Java-API#21]
Some method need to implements exceptions, specifically the vectors that have not the same size.

**Comment by dariomtz** [comment]
@natxsglez Isn't this solved with #27 ?

Can this be closed?

**Comment by natxsglez** [comment]
@dariomtz It isn't solved, I will close it when it gets done

**Comment by dariomtz** [comment]
Fixed in #27  and #30
